language: java
sudo: false
env:
  matrix:
    - PLATFORM=lucee452
before_install:
- mkdir /tmp/bin
- export PATH=$PATH:/tmp/bin
install:
- curl --location 'https://www.ortussolutions.com/parent/download/commandbox/type/bin' -o /tmp/box.zip
- unzip /tmp/box.zip -d /tmp/bin
- sed -i "s/java_args='-client'/java_args='-Xmx512m -client'/" /tmp/bin/box
- ant -f build/environment-runner/environment-runner.xml -Dplatform=$PLATFORM install
- box install

before_script:
- mysql -e 'create database coldboxtest;'
- ant -f build/environment-runner/environment-runner.xml -Dplatform=$PLATFORM start
script:
- ant -f build/coldbox.xml -Denvironment=travis run-tests
after_script:
- ant -f build/environment-runner/environment-runner.xml -Dplatform=$PLATFORM stop

notifications:
  email: false